# Generated by Django 5.2.7 on 2025-10-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hotel', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='roomcatalog',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stay_manager.hotelcatalog'),
            preserve_default=False,
        ),
    ]
