# Generated by Django 5.2.7 on 2025-10-12 04:34

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ("stay_manager", "0002_hotelcatalog_roomcatalog_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcatalog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
