# Generated by Django 5.2 on 2025-10-24 17:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_manager", "0003_roomcatalog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomcatalog",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
